//
// Created by jan on 07.03.17.
//

#ifndef JIMP_EXERCISES_MULTIPLICATIONTABLE_H
#define JIMP_EXERCISES_MULTIPLICATIONTABLE_H


void MultiplicationTable(int tab[][10]);


#endif //JIMP_EXERCISES_MULTIPLICATIONTABLE_H