//
// Created by janek on 14.03.17.
//

#ifndef JIMP_EXERCISES_MINIMALTIMEDIFFERENCE_H
#define JIMP_EXERCISES_MINIMALTIMEDIFFERENCE_H


class MinimalTimeDifference {

};


#endif //JIMP_EXERCISES_MINIMALTIMEDIFFERENCE_H
